In [52]:
#import packages
import numpy as np

In [53]:
#activation function
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [54]:
#derivative of activation function
def sigmoid_derivate(x):
    return x * (1 - x)

In [65]:
#defining input and output
training_inputs=np.array([[0,0,1],
                          [1,1,1],
                          [1,0,1],
                          [0,1,1]])

training_outputs=np.array([[1,1,1,0]]).T

In [69]:
#weight initialization
np.random.seed(1)
weights=2*np.random.random((3,1))-1
print('weights before training')
print(weights)

initial weights
[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]


In [71]:
#training
for iteration in range(100000):
    
    input_layer = training_inputs
    
    predictions=sigmoid(np.dot(input_layer, weights))
    
    error = training_outputs - predictions
    
    delta = error * sigmoid_derivate(predictions)
    
    weights += np.dot(input_layer.T, delta)
    



In [74]:
#printing outptut
print('weights after training') 
print(weights)


print('predictions after training')
print(predictions)

weights after training
[[ 11.84286498]
 [-11.63917941]
 [  5.89179511]]
predictions after training
[[0.99724559]
 [0.99775203]
 [0.99999998]
 [0.00318097]]
